### ISSUE TITLE
CellProfiler classify objects error

### ISSUE THREAD

**Issue by gterrierz** [gterrierz/CellProfiler#1]
Having issues with Classify Objects module. When in hidden mode, the analysis runs fine. When one view mode the following error message comes up;

> "Error while processing ClassifyObjects:
boolean index did not match indexed array along dimension 0; dimension is 'x+1' but corresponding boolean dimension is 'x'.
Do you want to stop processing?"

X is always different depending on the image i'm analysing.

Any help would be much appreciated as I would really like to view the output image in the ClassifyObjects module format, without having to view it in another module such as Crop.

**Comment by gterrierz** [comment]
The code in case it's useful:
`Failed to run module ClassifyObjects
Traceback (most recent call last):
  File "CellProfiler\cellprofiler\gui\pipelinecontroller.py", line 2926, in do_step
  File "CellProfiler\cellprofiler\modules\classifyobjects.py", line 561, in display
  File "CellProfiler\cellprofiler\modules\classifyobjects.py", line 668, in display_two_measurements
IndexError: boolean index did not match indexed array along dimension 0; dimension is 6 but corresponding boolean dimension is 5`
